# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://collide0412.github.io'
# Base URL of the Site (leave blank since this is your user site)
baseurl: ''

# Title of the Site
title: Tran Quoc Dang's Portfolio
# Description of the Site
description: A portfolio showcasing my education, work experience, projects, and skills
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Portfolio, Tran Quoc Dang, Data Engineer, Projects
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: collide0412@gmail.com
facebook_username: Collideee
instagram_username: cuoc_dangg
linkedin_username: collide0412
github_username: collide0412

# Name of the Author
author-name: Tran Quoc Dang
# URL for the Image of the Author
author-image: https://collide0412.github.io/assets/images/profile.jpg
# 60 Words About the Author
author-about: Data Engineer and aspiring professional with a passion for data science and technology. Currently pursuing a Bachelor's in Informatics and Computer Engineering at the International School, Vietnam National University.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/collide0412

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
 
